package toolbox.common.workflow.core;

public enum ActionLifecycle {
    WORKFLOW_STARTING, WORKFLOW_STARTED, WORKFLOW_FINISHING, WORKFLOW_FINISHED,
    PHASE_ENTERING, PHASE_ENTERED, PHASE_LEAVING, PHASE_LEFT, 
    TRANSITION_STARTING, TRANSITION_FINISHED
}
