package toolbox.common.workflow.core;

public enum ActionLifecycle {
    DOCUMENT_NEW, DOCUMENT_CREATING, DOCUMENT_CREATED, DOCUMENT_UPDATING, DOCUMENT_UPDATED, DOCUMENT_DELETING, DOCUMENT_DELETED,
    WORKFLOW_STARTING, WORKFLOW_STARTED, WORKFLOW_FINISHING, WORKFLOW_FINISHED,
    PHASE_ENTERING, PHASE_ENTERED, PHASE_LEAVING, PHASE_LEFT, 
    TRANSITION_STARTING, TRANSITION_FINISHED
}
